//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoldTiket
    {
        public int Id { get; set; }
        public int AbonementId { get; set; }
        public int PoolId { get; set; }
        public int UserId { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Abonement Abonement { get; set; }
        public virtual Pool Pool { get; set; }
        public virtual User User { get; set; }
    }
}
